version: '3'
services:
  webserver:
    build: .
    container_name: kata-test
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal